### ISSUE TITLE
EventBus doesn't have a slf4j log adapter

### ISSUE THREAD

**Issue by Dinnerbone** [mixer/interactive-java#64]
The default guava EventBus mangles exceptions and prints to console, which makes exceptions thrown during events very hard to track down.

Since this project is set up to use slf4j, an adaptor should be provided to the constructor of EventBus to log the actual exceptions.

**Comment by pahimar** [comment]
Resolved with switching back to log4j2 - https://github.com/mixer/interactive-java/commit/21ae1c32d6cb9372df7e395aaef16a64f8c9ab47
